### ISSUE TITLE
Index-Seite als Teil der Elternseiten behandeln

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/merger2#34]
Merger² kann ja Artikel erben von übergeordneten Seiten. Ich habe oft den Aufbau, dass ich einen Standard definiert habe (z.B. Header-Bild), den ich ggf. überschreiben möchte. Eigentlich will ich dies auf Ebene der Wurzelseite definieren, was bei Contao ja nicht geht. Daher ist meine Überlegung, ob man die Index-Seite immer so behandelt, dass diese mit berücksichtigt wird in der Vererbungs-Hierachie.

Ggf. könnte man dies konfigurierbar machen.

@zonky2 @baumannsven was denkt ihr?

**Comment by baumannsven** [comment]
@dmolineus Was verstehst du unter index Seite?

**Comment by dmolineus** [comment]
> @dmolineus Was verstehst du unter index Seite?

Die Startseite (die in der Regel den Alias index besitzt).

**Comment by baumannsven** [comment]
Beispiel:

```yml
merger2.index:
    - common: "index"
    - foo.bar: "foobar"
```

Der Key common gilt dann für nicht deklarierte DNS bzw. wenn keine andere gefunden wird.

**Comment by baumannsven** [comment]
Oder

```yml
merger2.index:
    common: "index"
    override:
         - foo.bar: "foobar"
```
